### ISSUE TITLE
請問聯繫表7的LINE通知內容

### ISSUE THREAD

**Issue by orzks** [mark2me/wp-line-notify#5]
請問聯繫表7的LINE通知是否可以跟WooCommerce通知一樣可以自訂內容

**Comment by mark2me** [comment]
WooCommerce 的標籤(變數)命名是固定的，Contact Form 7 的標籤命名可以自己變動，例如 [your-name] 可以改成 [your-nickname]。雖然大部分的使用者不會去改 [your-name]，但是還是有某些人會去修改或是新增自定義的標籤，這就無法得知他所改的變數名稱是什麼意義，因此要自定內容是無法達成的。

**Comment by mark2me** [comment]
在 1.3.3 更新了此問題
