### ISSUE TITLE
Error on send LINE Notify.

### ISSUE THREAD

**Issue by firforest1** [mark2me/wp-line-notify#6]
Hello,

I downloaded Line Notify plugin and installed to WordPress.
I also set up Line Notify token. It looks like "Access token valid"
However, when I tried to send a test message from "Test Line Notify", 
it returns "Error on send LINE Notify."
Do you what the problem is?
I am using WP 5.7.2 and Woocommerce 5.4.1

Thank you.

**Comment by mark2me** [comment]
Sorry, Has your problem been solved?

**Comment by graphiostudio** [comment]
I have the same issue. It can send notification on "1-on1 with line notification" but its got an error on trying to send another group. Any way to fix this?

**Comment by graphiostudio** [comment]
Argghhhh, it's stupid of me... I forgot to invite "Line Notify" to the group chat, that's why it's giving an error. All fixed now, thanks for this great little plugin :)
