### ISSUE TITLE
請問有辦法抓到 checkout field editor 表單裡面的值嗎 

### ISSUE THREAD

**Issue by Kennethvovo** [mark2me/wp-line-notify#8]
目前使用 checkout field editor 這個外掛在WooCommerce上面 ，請問有辦法抓到裡面的資料嗎

**Comment by mark2me** [comment]
請問你是要抓在 checkout field editor 自訂的欄位嗎？還是本來既有的欄位？

**Comment by Kennethvovo** [comment]
自訂的欄位

**Comment by mark2me** [comment]
已經發佈新版支援，若有問題再回覆
